/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFrame;

/**
 *
 * @author blazquez.asier
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerlabel = new javax.swing.JLabel();
        anadirCantidadButton = new javax.swing.JButton();
        manageProductsButton = new javax.swing.JButton();
        movementsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        depositDineroButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bannerlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bannerjava.png"))); // NOI18N
        getContentPane().add(bannerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        anadirCantidadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        anadirCantidadButton.setActionCommand("anadirCantidadMenu");
        anadirCantidadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirCantidadButtonActionPerformed(evt);
            }
        });
        getContentPane().add(anadirCantidadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 140, -1));

        manageProductsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/product.png"))); // NOI18N
        manageProductsButton.setActionCommand("Manage Products");
        manageProductsButton.setOpaque(false);
        manageProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageProductsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, 130));

        movementsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/movimientos.png"))); // NOI18N
        movementsButton.setActionCommand("verMovimientos");
        movementsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movementsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(movementsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 130, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Manage Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Add Quantity");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 120, 30));

        depositDineroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money.png"))); // NOI18N
        depositDineroButton.setActionCommand("Deposit Money");
        depositDineroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositDineroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(depositDineroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 130, 120));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Movements");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Deposit Money");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 120, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 700, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirCantidadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirCantidadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anadirCantidadButtonActionPerformed

    private void movementsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movementsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movementsButtonActionPerformed

    private void depositDineroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositDineroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositDineroButtonActionPerformed

    private void manageProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductsButtonActionPerformed

    }//GEN-LAST:event_manageProductsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static Menu MenuaSortuBistaratu() {
        Menu m = new Menu();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                m.setVisible(true);
            }
        });
        return m;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton anadirCantidadButton;
    public javax.swing.JLabel bannerlabel;
    public javax.swing.JButton depositDineroButton;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JButton manageProductsButton;
    public javax.swing.JButton movementsButton;
    // End of variables declaration//GEN-END:variables
}
